// packages/playground-next/src/components/mj-modal.tsx
import { Dialog, Transition } from '@headlessui/react'
import clsx from 'clsx'
import { Fragment } from 'react'
import { XMarkIcon } from '@heroicons/react/24/solid'

export default function MjModal({
  show,
  setOpen,
  title,
  panelClass,
  fullscreen,
  children
}: {
  show: boolean
  setOpen: (val: boolean) => void
  title: string
  panelClass?: string
  fullscreen?: boolean
  children: React.ReactNode
}) {
  return (
    <Transition.Root appear show={show} as={Fragment}>
      <Dialog open={show} onClose={setOpen} className="relative z-50">
        <Transition.Child
          as={Fragment}
          enter="duration-300 ease-out"
          enter-from="opacity-0"
          enter-to="opacity-100"
          leave="duration-200 ease-in"
          leave-from="opacity-100"
          leave-to="opacity-0"
        >
          <div className="fixed inset-0 bg-gray-600/60" />
        </Transition.Child>
        <div className="fixed inset-0 overflow-y-auto">
          <div
            className={clsx(
              'flex min-h-full justify-center',
              fullscreen ? 'h-full items-stretch' : 'p-4 items-center'
            )}
          >
            <Transition.Child
              as={Fragment}
              enter="duration-300 ease-out"
              enter-from="opacity-0 scale-95"
              enter-to="opacity-100 scale-100"
              leave="duration-200 ease-in"
              leave-from="opacity-100 scale-100"
              leave-to="opacity-0 scale-95"
            >
              <Dialog.Panel
                className={clsx(
                  'bg-white p-6 shadow-xl transition-all w-full flex flex-col gap-2 overflow-hidden',
                  !fullscreen && 'rounded-md',
                  panelClass
                )}
              >
                <Dialog.Title className="text-lg font-medium leading-6 text-gray-900 flex items-center justify-between z-50">
                  <span>{title}</span>
                  <XMarkIcon
                    className="w-5 h-5"
                    onClick={() => setOpen(false)}
                  />
                </Dialog.Title>
                {children}
              </Dialog.Panel>
            </Transition.Child>
          </div>
        </div>
      </Dialog>
    </Transition.Root>
  )
}

// packages/playground/src/components/MjModal/index.vue
<template>
  <TransitionRoot appear :show="show" as="template">
    <Dialog :open="show" @close="show = false" class="relative z-50">
      <TransitionChild
        as="template"
        enter="duration-300 ease-out"
        enter-from="opacity-0"
        enter-to="opacity-100"
        leave="duration-200 ease-in"
        leave-from="opacity-100"
        leave-to="opacity-0"
      >
        <div class="fixed inset-0 bg-gray-600/60" />
      </TransitionChild>

      <div class="fixed inset-0 overflow-y-auto">
        <div
          :class="[
            'flex min-h-full justify-center',
            fullscreen ? 'h-full items-stretch' : 'p-4 items-center'
          ]"
        >
          <TransitionChild
            as="template"
            enter="duration-300 ease-out"
            enter-from="opacity-0 scale-95"
            enter-to="opacity-100 scale-100"
            leave="duration-200 ease-in"
            leave-from="opacity-100 scale-100"
            leave-to="opacity-0 scale-95"
          >
            <DialogPanel
              :class="[
                'bg-white p-6 shadow-xl transition-all w-full flex flex-col gap-2 overflow-hidden',
                !fullscreen && 'rounded-md',
                panelClass
              ]"
            >
              <DialogTitle
                class="text-lg font-medium leading-6 text-gray-900 flex items-center justify-between z-50"
              >
                <span>{{ title }}</span>
                <XMarkIcon class="w-5 h-5" @click="show = false" />
              </DialogTitle>
              <slot v-if="$slots.default" />
            </DialogPanel>
          </TransitionChild>
        </div>
      </div>
    </Dialog>
  </TransitionRoot>
</template>

<script setup lang="ts">
import { XMarkIcon } from '@heroicons/vue/24/solid'
defineProps<{ title: string; panelClass?: string; fullscreen?: boolean }>()
const show = defineModel<boolean>('show', { required: true })
</script>
