// packages/playground-vue/src/components/InpaintingEditor/index.vue
<template>
  <div class="flex-1 flex items-center justify-center absolute inset-0 h-full">
    <canvas
      ref="canvas"
      hidpi="on"
      width="1024"
      height="1024"
      resize
      style="padding: 0px; margin: 0px; width: 100%; max-width: 960px"
    ></canvas>
  </div>
  <div class="fixed top-20 left-3 flex justify-center items-center">
    <button class="btn border" @click="paper?.undo">
      <SvgIcon icon-class="undo" class="w-5 h-5"></SvgIcon>
    </button>
  </div>
  <div
    id="appbody"
    class="flex fixed inset-x-0 bottom-0 w-full items-end justify-between p-3 border gap-4"
  >
    <div class="flex gap-2">
      <button
        v-for="(v, i) in btns"
        :key="i"
        :class="['btn', selectedTool === v.value && '!bg-gray-400']"
        @click="paper && (paper.selectedTool = v.value)"
      >
        <SvgIcon :icon-class="v.label" class="w-5 h-5"></SvgIcon>
      </button>
    </div>
    <div class="flex items-end flex-1 gap-4">
      <textarea
        v-model="input"
        ref="textarea"
        class="resize-none overflow-hidden flex-1 !border-gray-200 rounded"
        placeholder="send a prompt"
      ></textarea>
      <button class="btn flex-shrink-0" @click="handleSubmit">
        <SvgIcon icon-class="send" class="w-5 h-5"></SvgIcon>
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
const emits = defineEmits<{
  (e: 'submit', mask: string, prompt: string): void
}>()
import { MjPaper } from '@/utils/paper'
const mj = useMjStore()
const canvas = ref<HTMLCanvasElement>()
const { input, textarea } = useTextareaAutosize({
  input: mj.varyRegionInfo.varyRegionPrompt
})
const paper = ref<MjPaper>()
const btns = reactive([
  { label: 'rect', value: 0 },
  { label: 'lasso', value: 0.5 }
] as const)
const selectedTool = computed(() => paper.value?.selectedTool)
const getImg = () =>
  new Promise<HTMLImageElement>((s) => {
    const img = new Image()
    img.src = mj.varyRegionInfo.varyRegionImgBase64
    img.onload = () => s(img)
  })

const handleSubmit = () => {
  if (!input.value.trim()) {
    MjToast({ msg: 'image prompt is required', type: 'error', duration: 3000 })
    return
  }
  paper.value
    ?.submit()
    .then((mask) => {
      emits('submit', mask, input.value)
    })
    .catch((errMsg) => {
      MjToast({ msg: errMsg, type: 'error', duration: 3000 })
    })
}
onMounted(async () => {
  if (canvas.value) {
    const img = await getImg()
    paper.value = new MjPaper(canvas.value, img)
  }
})
</script>

<style scoped>
.btn {
  @apply p-2 rounded-full bg-gray-400/70 text-white;
}
</style>

// packages/playground-next/src/components/inpainting-editor.tsx
import { MjPaper } from '@/utils/paper'
import TextareaAutosize from 'react-textarea-autosize'
import Undo from '@/icons/undo.svg'
import Send from '@/icons/send.svg'
import Rect from '@/icons/rect.svg'
import Lasso from '@/icons/lasso.svg'
import { useEffect, useRef, useState } from 'react'
import { useMjStore } from '@/stores/mj'
import clsx from 'clsx'

export default function InpaintingEditor({
  submit
}: {
  submit: (mask: string, prompt: string) => void
}) {
  const [paper, setPaper] = useState<MjPaper | null>(null)
  const canvas = useRef<HTMLCanvasElement>(null)
  const varyRegionInfo = useMjStore((state) => state.varyRegionInfo)
  const [input, setInput] = useState(varyRegionInfo.varyRegionPrompt)
  const btns = [
    { label: 'rect', value: 0, icon: Rect },
    { label: 'lasso', value: 0.5, icon: Lasso }
  ] as const
  const getImg = () =>
    new Promise<HTMLImageElement>((s) => {
      const img = new Image()
      img.src = varyRegionInfo.varyRegionImgBase64
      img.onload = () => s(img)
    })
  const init = async () => {
    if (canvas.current) {
      const img = await getImg()
      const paper = new MjPaper(canvas.current, img)
      setPaper(paper)
    }
  }
  const handleSubmit = () => {
    if (!input.trim()) {
      //   MjToast({
      //     msg: 'image prompt is required',
      //     type: 'error',
      //     duration: 3000
      //   })
      return
    }
    paper
      ?.submit()
      .then((mask) => submit(mask, input))
      .catch((errMsg) => {
        // MjToast({ msg: errMsg, type: 'error', duration: 3000 })
      })
  }
  useEffect(() => {
    init()
  }, [])
  return (
    <>
      <div className="flex-1 flex items-center justify-center absolute inset-0 h-full">
        <canvas
          //@ts-ignore
          hidpi="on"
          ref={canvas}
          width="1024"
          height="1024"
          resize="true"
          style={{
            padding: '0px',
            margin: '0px',
            width: '100%',
            maxWidth: '960px'
          }}
        ></canvas>
      </div>
      <div className="fixed top-20 left-3 flex justify-center items-center">
        <button className="editor-btn border" onClick={() => paper?.undo()}>
          <Undo className="w-5 h-5" />
        </button>
      </div>
      <div
        id="appbody"
        className="flex fixed inset-x-0 bottom-0 w-full items-end justify-between p-3 border gap-4"
      >
        <div className="flex gap-2">
          {btns.map((v, i) => (
            <button
              key={i}
              className={clsx(
                'editor-btn',
                paper?.selectedTool === v.value && '!bg-gray-400'
              )}
              onClick={() => {
                paper &&
                  setPaper((paper) =>
                    Object.assign(paper!, { selectedTool: v.value })
                  )
              }}
            >
              <v.icon className="w-5 h-5" />
            </button>
          ))}
        </div>
        <div className="flex items-end flex-1 gap-4">
          <TextareaAutosize
            value={input}
            rows={1}
            className="resize-none overflow-hidden flex-1 !border-gray-200 rounded"
            placeholder="send a prompt"
            onChange={(e) => setInput(e.target.value)}
          />
          <button className="editor-btn flex-shrink-0" onClick={handleSubmit}>
            <Send className="w-5 h-5" />
          </button>
        </div>
      </div>
    </>
  )
}
