// packages/playground/src/components/MjForm/index.vue
<template>
  <form @submit.prevent="mj.init(form)" class="flex flex-col gap-4 p-4">
    <div class="form-item" required>
      <label>Guild's id</label>
      <input
        v-model="form.guild_id"
        type="text"
        placeholder="please input your guild_id"
      />
    </div>
    <div class="form-item" required>
      <label>Channel's id</label>
      <input
        v-model="form.channel_id"
        type="text"
        placeholder="please input your channel_id"
      />
    </div>
    <div class="form-item" required>
      <label>User's Token</label>
      <input
        v-model="form.token"
        type="text"
        placeholder="please input your token"
      />
    </div>
    <div class="form-item">
      <label>DiscordApi's BaseUrl</label>
      <input
        v-model="form.apiBaseUrl"
        type="text"
        placeholder="DiscordApi's BaseUrl"
      />
    </div>
    <div class="form-item">
      <label>DiscordWs's BaseUrl</label>
      <input
        v-model="form.wsBaseUrl"
        type="text"
        placeholder="DiscordWs's BaseUrl"
      />
    </div>
    <div class="form-item">
      <label>DiscordImage's BaseApi</label>
      <input
        v-model="form.imgBaseUrl"
        type="text"
        placeholder="DiscordImage's BaseApi"
      />
    </div>
    <button type="submit" class="border border-gray-500 rounded-md p-2">
      Submit
    </button>
  </form>
</template>

<script setup lang="ts">
import { MidJourneyOptions, defaultOpts } from 'midjourney-sdk'
const mj = useMjStore()
const form = reactive<MidJourneyOptions>({
  token: import.meta.env.VITE_TOKEN,
  guild_id: import.meta.env.VITE_GUILD_ID,
  channel_id: import.meta.env.VITE_CHANNEL_ID,
  apiBaseUrl: import.meta.env.VITE_API_BASE_URL || defaultOpts.apiBaseUrl,
  imgBaseUrl: import.meta.env.VITE_IMG_BASE_URL || defaultOpts.imgBaseUrl,
  wsBaseUrl: import.meta.env.VITE_WS_BASE_URL || defaultOpts.wsBaseUrl
})
</script>

<style scoped>
.form-item {
  @apply flex md:items-center flex-col md:flex-row gap-2;
}
.form-item[required] label {
  @apply before:content-['*'] before:text-red-500;
}
.form-item input {
  @apply flex-1 bg-transparent rounded-md;
}
.form-item label {
  @apply min-w-[100px];
}
</style>

// packages/playground-next/src/components/mj-form.tsx
import { MidJourneyOptions, defaultOpts } from 'midjourney-sdk'
import { useState } from 'react'
import { useMjStore } from '@/stores/mj'

export default function MjForm() {
  const init = useMjStore((state) => state.init)
  const [form, setForm] = useState<MidJourneyOptions>({
    token: process.env.NEXT_PUBLIC_TOKEN as string,
    guild_id: process.env.NEXT_PUBLIC_GUILD_ID as string,
    channel_id: process.env.NEXT_PUBLIC_CHANNEL_ID as string,
    apiBaseUrl:
      (process.env.NEXT_PUBLIC_API_BASE_URL as string) ||
      defaultOpts.apiBaseUrl,
    imgBaseUrl:
      (process.env.NEXT_PUBLIC_IMG_BASE_URL as string) ||
      defaultOpts.imgBaseUrl,
    wsBaseUrl:
      (process.env.NEXT_PUBLIC_WS_BASE_URL as string) || defaultOpts.wsBaseUrl
  })
  return (
    <form
      onSubmit={(e) => {
        e.preventDefault()
        init(form)
      }}
      className="flex flex-col gap-4 p-4"
    >
      <div className="form-item">
        <label>Guild's id</label>
        <input
          value={form.guild_id}
          onChange={(e) =>
            setForm((state) => ({ ...state, guild_id: e.target.value }))
          }
          type="text"
          placeholder="please input your guild_id"
        />
      </div>
      <div className="form-item">
        <label>Channel's id</label>
        <input
          value={form.channel_id}
          onChange={(e) =>
            setForm((state) => ({ ...state, channel_id: e.target.value }))
          }
          type="text"
          placeholder="please input your channel_id"
        />
      </div>
      <div className="form-item">
        <label>User's Token</label>
        <input
          value={form.token}
          onChange={(e) =>
            setForm((state) => ({ ...state, token: e.target.value }))
          }
          type="text"
          placeholder="please input your token"
        />
      </div>
      <div className="form-item">
        <label>DiscordApi's BaseUrl</label>
        <input
          value={form.apiBaseUrl}
          onChange={(e) =>
            setForm((state) => ({ ...state, apiBaseUrl: e.target.value }))
          }
          type="text"
          placeholder="DiscordApi's BaseUrl"
        />
      </div>
      <div className="form-item">
        <label>DiscordWs's BaseUrl</label>
        <input
          value={form.wsBaseUrl}
          onChange={(e) =>
            setForm((state) => ({ ...state, wsBaseUrl: e.target.value }))
          }
          type="text"
          placeholder="DiscordWs's BaseUrl"
        />
      </div>
      <div className="form-item">
        <label>DiscordImage's BaseApi</label>
        <input
          value={form.imgBaseUrl}
          onChange={(e) =>
            setForm((state) => ({ ...state, imgBaseUrl: e.target.value }))
          }
          type="text"
          placeholder="DiscordImage's BaseApi"
        />
      </div>
      <button type="submit" className="border border-gray-500 rounded-md p-2">
        Submit
      </button>
    </form>
  )
}
