// packages/playground/src/components/Welcome/index.vue
<template>
  <img src="/mj.png" class="w-16 h-16 rounded-full m-auto mb-5" />
  <h1 class="text-center text-2xl font-bold">Midjourney-SDK Example</h1>
  <a
    href="https://github.com/LaiBaoYuan/midjourney-sdk"
    class="text-center underline m-auto block mb-5"
    target="_blank"
    >It's useful for you, please give me open source power and support star in
    my `midjourney-sdk` repo.</a
  >
</template>

<script setup lang="ts"></script>

<style scoped></style>

// packages/playground-next/src/components/welcome.tsx
export default function Welcome() {
  return (
    <>
      <img src="/mj.png" className="w-16 h-16 rounded-full m-auto mb-5" />
      <h1 className="text-center text-2xl font-bold">Midjourney-SDK Example</h1>
      <a
        href="https://github.com/LaiBaoYuan/midjourney-sdk"
        className="text-center underline m-auto block mb-5"
        target="_blank"
      >
        It's useful for you, please give me open source power and support star
        in my `midjourney-sdk` repo.
      </a>
    </>
  )
}
